### ISSUE TITLE
Feature request: brightness setting when battery powered

### ISSUE THREAD

**Issue by limpkin** [mooltipass/minible#267]
should be relatively easy :)

**Comment by hijackeel** [comment]
How about having this configurable while plugged in too? It's too bright if I'm trying to sleep while it does a battery reconditioning. Amazingly, even when I flip it upside down, too much light bleeds through the translucent silicone case, and I have to shove it in a drawer which I can't close properly because of the cable.

**Comment by limpkin** [comment]
yep, that's definitely doable :)

**Comment by limpkin** [comment]
on moolticute side: https://github.com/mooltipass/moolticute/issues/890
